package kr.timehub.beplan.utils;

import android.graphics.Typeface;
import java.util.HashMap;

/* loaded from: classes.dex */
public class Comm_Params {
    public static final String ACTION_MAIN_DRAWER_CLOSE = "kr.timehub.beplan.ACTION_MAIN_DRAWER_CLOSE";
    public static final String ACTION_MAIN_DRAWER_OPEN = "kr.timehub.beplan.ACTION_MAIN_DRAWER_OPEN";
    public static final String DEVICE_PART = "A";
    public static final int FONT_TYPE_NANUM_BOLD = 1;
    public static final int FONT_TYPE_NANUM_LIGHT = 2;
    public static final int FONT_TYPE_NANUM_REGULAR = 0;
    public static final String GOOGLE_API_KEY_SERVER = "368687737953-lvlofaermlr9bm9nco4pocdhn28bemhg.apps.googleusercontent.com";
    public static final int LOGIN_TYPE_FORGOT_EMAIL = 2;
    public static final int LOGIN_TYPE_LOGIN = 0;
    public static final int LOGIN_TYPE_REGISTER = 1;
    public static final int NETWORK_TIMEOUT = 5000;
    public static final String NOTIFICATION_ID_DEFAULT_ALARM = "id_default_alarm";
    public static final String PUSH_RECEIVE = "PUSH_RECEIVE";
    public static final String TAG = "Beplan";
    public static final String URL_API_MYFORM_FORMLIST;
    public static final String URL_API_MYFORM_POP_TASKLIST;
    public static final String URL_API_MYFORM_USING;
    public static final String URL_API_PROJECT_PROJECTLIST_FORM;
    public static final String URL_API_PROJECT_SHAREDPROJECTDETAIL;
    public static final String URL_API_SHOP_BUYPROJECT;
    public static final String URL_API_SHOP_INDEX;
    public static final String URL_API_TASK_UPTTASKSTATESUCCESS;
    public static final String URL_KEYWORD = "?keyword=";
    public static final String URL_MTTSEQ = "?MTTSEQ=";
    public static final String URL_PARAM_MTTSEQ = "{MTTSEQ}";
    public static final Boolean IS_REAL_SERVER_TEST = true;
    public static final HashMap<Integer, Typeface> FONTS = new HashMap<>();
    public static final String[] APP_PERMISSIONS = {"android.permission.WRITE_EXTERNAL_STORAGE", "android.permission.READ_EXTERNAL_STORAGE", "android.permission.CAMERA", "android.permission.RECORD_AUDIO"};
    public static final String URL_HOST = "http://mapi.beplan.kr/";
    public static final String URL_API = URL_HOST + "api/";
    public static final String URL_SSO = "https://secure.timehub.kr/";
    public static final String URL_SSO_ACCOUNT = URL_SSO + "Account/";
    public static final String URL_API_MYINFO = URL_API + "MyInfo/";
    public static final String URL_API_MYINFO_POP_MYINFO = URL_API_MYINFO + "Pop_MyInfo";
    public static final String URL_API_MYINFO_CHANGE_NAME = URL_API_MYINFO + "Change_Name";
    public static final String URL_API_MYINFO_CHANGE_PROFILE = URL_API_MYINFO + "Change_Profile";
    public static final String URL_SSO_ACCOUNT_REGISTER = URL_SSO_ACCOUNT + "Register";
    public static final String URL_SSO_ACCOUNT_LOGIN = URL_SSO_ACCOUNT + "Login";
    public static final String URL_SSO_ACCOUNT_PROVISION = URL_SSO_ACCOUNT + "Provision";
    public static final String URL_SSO_ACCOUNT_FORGOTPASSWORD = URL_SSO_ACCOUNT + "ForgotPassword";
    public static final String URL_API_TEAMS = URL_API + "Teams/";
    public static final String URL_API_TEAMS_TEAMPREVIEW = URL_API_TEAMS + "TeamPreview";
    public static final String URL_API_TEAMS_TEAMDETAILPOPUP = URL_API_TEAMS + "TeamDetailPopUp";
    public static final String URL_API_MAIN = URL_API + "Main/";
    public static final String URL_API_MAIN_INDEX = URL_API_MAIN + "Index";
    public static final String URL_API_MAIN_NEWINDEX = URL_API_MAIN + "NewIndex";
    public static final String URL_API_MAIN_NOTIFY_RECEIVEID = URL_API_MAIN + "Notify?ReceiveID=%s";
    public static final String URL_API_PROJECT = URL_API + "Project/";
    public static final String URL_API_PROJECT_INIT_PROJECT = URL_API_PROJECT + "Init_Project";
    public static final String URL_API_PROJECT_CREATE_PROJECT = URL_API_PROJECT + "Create_Project";
    public static final String URL_API_PROJECT_ADD_TEAMMEMBER = URL_API_PROJECT + "Add_TeamMember";
    public static final String URL_API_PROJECT_ADDTEAMMEMBEREMAIL = URL_API_PROJECT + "AddTeamMemberEmail";
    public static final String URL_API_TEAMS_MAKETEAM = URL_API_TEAMS + "MakeTeam";
    public static final String URL_API_TEAMS_TEAMCHANGE = URL_API_TEAMS + "TeamChange";
    public static final String URL_API_NOTIFICATION = URL_API + "Notification/";
    public static final String URL_API_NOTIFICATION_RECEIVE_NOTIFICATION = URL_API_NOTIFICATION + "Receive_Notification";
    public static final String URL_NSEQ = "?NSEQ=";
    public static final String URL_PARAM_NSEQ = "{NSEQ}";
    public static final String URL_API_NOTIFICATION_READ_NOTIFICATION = URL_API_NOTIFICATION + "ReadNotification" + URL_NSEQ + URL_PARAM_NSEQ;
    public static final String URL_API_PROJECT_PROJECTLIST = URL_API_PROJECT + "ProjectList";
    public static final String URL_API_PROJECT_MYPROJECTLIST = URL_API_PROJECT + "MyProjectList";
    public static final String URL_API_PROJECT_MYTASKSENDLIST = URL_API_PROJECT + "MyTaskSendList";
    public static final String URL_API_PROJECT_NEWMYTASKSENDLIST = URL_API_PROJECT + "NewMyTaskSendList";
    public static final String URL_API_PROJECT_MYYASKRECEIVELIST = URL_API_PROJECT + "MyTaskReceiveList";
    public static final String URL_API_PROJECT_NEWMYTASKRECEIVELIST = URL_API_PROJECT + "NewMyTaskReceiveList";
    public static final String URL_API_PROJECT_ADDPROJECTMEMBER = URL_API_PROJECT + "AddProjectMember";
    public static final String URL_API_PROJECT_UPTINVITESTATEACCEPT = URL_API_PROJECT + "UptInviteStateAccept";
    public static final String URL_API_PROJECT_UPTINVITESTATEREFUSE = URL_API_PROJECT + "UptInviteStateRefuse";
    public static final String URL_API_PROJECT_CHANGEPROJECTINFO = URL_API_PROJECT + "ChangeProjectInfo";
    public static final String URL_API_PROJECT_DELETEPROJECT = URL_API_PROJECT + "DeleteProject";
    public static final String URL_API_PROJECT_DELETECATEGORY = URL_API_PROJECT + "DeleteCategory";
    public static final String URL_API_PROJECT_PUTINTEMPLATE = URL_API_PROJECT + "PutInTemplate";
    public static final String URL_PSEQ = "?PSEQ=";
    public static final String URL_PARAM_PSEQ = "{PSEQ}";
    public static final String URL_AND_KEYWORD = "&keyword=";
    public static final String URL_PARAM_KEYWORD = "{keyword}";
    public static final String URL_API_PROJECT_PUTINTEMPLATE_GET_LIST = URL_API_PROJECT + "PutInTemplate" + URL_PSEQ + URL_PARAM_PSEQ + URL_AND_KEYWORD + URL_PARAM_KEYWORD;
    public static final String URL_API_CATEGORY = URL_API + "Category/";
    public static final String URL_API_CATEGORY_MODIFYCATEGORYTITLE = URL_API_CATEGORY + "ModifyCategoryTitle";
    public static final String URL_API_CATEGORY_MODIFYCATEGORYRUNNER = URL_API_CATEGORY + "ModifyCategoryRunner";
    public static final String URL_API_CATEGORY_PUTINTEMPLATECATEGORY = URL_API_CATEGORY + "PutInTemplateCateGory";
    public static final String URL_API_TASK = URL_API + "Task/";
    public static final String URL_API_TASK_DETAIL = URL_API_TASK + "Detail";
    public static final String URL_API_TASK_SENDCOMMENT = URL_API_TASK + "SendComment";
    public static final String URL_API_TASK_MAKECATEGORY = URL_API_TASK + "MakeCategory";
    public static final String URL_API_NEW_MAKECATEGORY = URL_API_TASK + "MakeCategoryNew";
    public static final String URL_API_TASK_MAKETASK = URL_API_TASK + "MakeTask";
    public static final String URL_API_TASK_UPTTASKSTATEREFUSE = URL_API_TASK + "UptTaskStateRefuse";
    public static final String URL_API_TASK_UPTTASKSTATEACCEPT = URL_API_TASK + "UptTaskStateAccept";
    public static final String URL_API_TASK_UPTTASKSTATECANCEL = URL_API_TASK + "UptTaskStateCancel";
    public static final String URL_PARAM_ID = "{Id}";
    public static final String URL_API_TASK_DELETETASK = URL_API_TASK + "DeleteTask/" + URL_PARAM_ID;
    public static final String URL_API_TASK_DELETECONTENTS = URL_API_TASK + "DeleteContents";
    public static final String URL_API_TASK_DELETETASKCOMMENT = URL_API_TASK + "DeleteTaskComment";
    public static final String URL_WORK = "http://work.beplan.kr/";
    public static final String URL_WORK_PROJECT_HISTORY = URL_WORK + "Project/History";
    @Deprecated
    public static final String URL_API_TASK_POP_DETAIL = URL_API_TASK + "Pop_Detail";
    public static final String URL_API_TASK_POP_RECEIVEDETAIL = URL_API_TASK + "Pop_ReceiveDetail";
    public static final String URL_API_TASK_POP_SENDDETAIL = URL_API_TASK + "Pop_SendDetail";
    public static final String URL_API_TASK_MAKE_TASK = URL_API_TASK + "MakeTask";
    public static final String URL_API_FILE = URL_API + "File/";
    public static final String URL_API_FILE_POSTFILE = URL_API_FILE + "PostFile";
    public static final String URL_API_FILE_MULTIPOSTFILE = URL_API_FILE + "MultiPostFile";
    public static final String URL_API_MYFORM = URL_API + "MyForm/";
    public static final String URL_MTCSEQ = "?MTCSEQ=";
    public static final String URL_PARAM_MTCSEQ = "{MTCSEQ}";
    public static final String URL_API_MYFORM_INDEX = URL_API_MYFORM + "Index" + URL_MTCSEQ + URL_PARAM_MTCSEQ + URL_AND_KEYWORD + URL_PARAM_KEYWORD;
    public static final String URL_MTPSEQ = "?MTPSEQ=";
    public static final String URL_PARAM_MTPSEQ = "{MTPSEQ}";
    public static final String URL_API_MYFORM_TASKDETAIL = URL_API_MYFORM + "TaskDetail" + URL_MTPSEQ + URL_PARAM_MTPSEQ + URL_AND_KEYWORD + URL_PARAM_KEYWORD;
    public static final String URL_API_MYFORM_CATEGORYDETAIL = URL_API_MYFORM + "CategoryDetail" + URL_MTCSEQ + URL_PARAM_MTCSEQ + URL_AND_KEYWORD + URL_PARAM_KEYWORD;
    public static final String URL_API_MYFORM_DELETEPROJECT = URL_API_MYFORM + "DeleteProject" + URL_MTPSEQ + URL_PARAM_MTPSEQ;
    public static final String URL_MTCGSEQ = "?MTCGSEQ=";
    public static final String URL_PARAM_MTCGSEQ = "{MTCGSEQ}";
    public static final String URL_API_MYFORM_DELETECATEGORY = URL_API_MYFORM + "DeleteCategory" + URL_MTCGSEQ + URL_PARAM_MTCGSEQ;
    public static final String URL_AND_MTCGSEQ = "&MTCGSEQ=";
    public static final String URL_API_MYFORM_POP_USING = URL_API_MYFORM + "Pop_Using" + URL_MTPSEQ + URL_PARAM_MTPSEQ + URL_AND_MTCGSEQ + URL_PARAM_MTCGSEQ;
    public static final String URL_API_MYSUBSCRIPTION = URL_API + "MySubscription/";
    public static final String URL_API_MYSUBSCRIPTION_PROJECTLIST = URL_API_MYSUBSCRIPTION + "ProjectList";
    public static final String URL_API_MYSUBSCRIPTION_CATEGORYLIST = URL_API_MYSUBSCRIPTION + "CategoryList";
    public static final String URL_API_MYSUBSCRIPTION_PROJECTDETAIL = URL_API_MYSUBSCRIPTION + "ProjectDetail";
    public static final String URL_API_MYSUBSCRIPTION_CATEGORYDETAIL = URL_API_MYSUBSCRIPTION + "CategoryDetail";
    public static final String URL_API_MYSUBSCRIPTION_SELECTCATEGORYVERSION = URL_API_MYSUBSCRIPTION + "SelectCategoryVersion";
    public static final String URL_API_MYSUBSCRIPTION_USINGPROJECT = URL_API_MYSUBSCRIPTION + "UsingProject";
    public static final String URL_API_MYSUBSCRIPTION_USINGCATEGORYS = URL_API_MYSUBSCRIPTION + "UsingCategorys";
    public static final String URL_API_SHOP = URL_API + "Shop/";
    public static final String URL_SMCSEQ = "?SMCSEQ=";
    public static final String URL_PARAM_SMCSEQ = "{SMCSEQ}";
    public static final String URL_API_SHOP_SHOPPROJECT = URL_API_SHOP + "ShopProject" + URL_SMCSEQ + URL_PARAM_SMCSEQ + URL_AND_KEYWORD + URL_PARAM_KEYWORD;
    public static final String URL_SPSEQ = "?SPSEQ=";
    public static final String URL_PARAM_SPSEQ = "{SPSEQ}";
    public static final String URL_API_SHOP_PROJECTDETAIL = URL_API_SHOP + "ProjectDetail" + URL_SPSEQ + URL_PARAM_SPSEQ + URL_AND_KEYWORD + URL_PARAM_KEYWORD;
    public static final String URL_API_SHOP_CATEGORYDETAIL = URL_API_SHOP + "CategoryDetail" + URL_SMCSEQ + URL_PARAM_SMCSEQ + URL_AND_KEYWORD + URL_PARAM_KEYWORD;
    public static final String URL_SCGSEQ = "?SCGSEQ=";
    public static final String URL_PARAM_SCGSEQ = "{SCGSEQ}";
    public static final String URL_API_SHOP_BUYCATEGORY = URL_API_SHOP + "BuyCateGory" + URL_SCGSEQ + URL_PARAM_SCGSEQ;
    public static final String URL_STSEQ = "?STSEQ=";
    public static final String URL_PARAM_STSEQ = "{STSEQ}";
    public static final String URL_API_SHOP_POP_TASKLIST = URL_API_SHOP + "Pop_TaskList" + URL_STSEQ + URL_PARAM_STSEQ;

    static {
        StringBuilder sb = new StringBuilder();
        sb.append(URL_API_PROJECT);
        sb.append("ProjectListForm");
        URL_API_PROJECT_PROJECTLIST_FORM = sb.toString();
        StringBuilder sb2 = new StringBuilder();
        sb2.append(URL_API_PROJECT);
        sb2.append("SharedProjectDetail");
        URL_API_PROJECT_SHAREDPROJECTDETAIL = sb2.toString();
        StringBuilder sb3 = new StringBuilder();
        sb3.append(URL_API_TASK);
        sb3.append("UptTaskStateSuccess");
        URL_API_TASK_UPTTASKSTATESUCCESS = sb3.toString();
        StringBuilder sb4 = new StringBuilder();
        sb4.append(URL_API_MYFORM);
        sb4.append("FormList");
        sb4.append(URL_KEYWORD);
        sb4.append(URL_PARAM_KEYWORD);
        URL_API_MYFORM_FORMLIST = sb4.toString();
        StringBuilder sb5 = new StringBuilder();
        sb5.append(URL_API_MYFORM);
        sb5.append("Pop_TaskList");
        sb5.append(URL_MTTSEQ);
        sb5.append(URL_PARAM_MTTSEQ);
        URL_API_MYFORM_POP_TASKLIST = sb5.toString();
        StringBuilder sb6 = new StringBuilder();
        sb6.append(URL_API_MYFORM);
        sb6.append("Using");
        URL_API_MYFORM_USING = sb6.toString();
        StringBuilder sb7 = new StringBuilder();
        sb7.append(URL_API_SHOP);
        sb7.append("Index");
        sb7.append(URL_KEYWORD);
        sb7.append(URL_PARAM_KEYWORD);
        URL_API_SHOP_INDEX = sb7.toString();
        StringBuilder sb8 = new StringBuilder();
        sb8.append(URL_API_SHOP);
        sb8.append("BuyProject");
        sb8.append(URL_SPSEQ);
        sb8.append(URL_PARAM_SPSEQ);
        URL_API_SHOP_BUYPROJECT = sb8.toString();
    }
}
