package com.naver.temy123.baseproject.base.Http;

import java.util.HashMap;

/* loaded from: classes.dex */
public class HWOkHttpMimeType {
    public static final String MIME_APPLICATION_ANDREW_INSET = "application/andrew-inset";
    public static final String MIME_APPLICATION_JAVA_ARCHIVE = "application/java-archive";
    public static final String MIME_APPLICATION_JNLP = "application/jnlp";
    public static final String MIME_APPLICATION_JSON = "application/json";
    public static final String MIME_APPLICATION_MAC_BINHEX40 = "application/mac-binhex40";
    public static final String MIME_APPLICATION_MAC_COMPACTPRO = "application/mac-compactpro";
    public static final String MIME_APPLICATION_MATHML_XML = "application/mathml+xml";
    public static final String MIME_APPLICATION_MSWORD = "application/msword";
    public static final String MIME_APPLICATION_OCTET_STREAM = "application/octet-stream";
    public static final String MIME_APPLICATION_ODA = "application/oda";
    public static final String MIME_APPLICATION_PDF = "application/pdf";
    public static final String MIME_APPLICATION_POSTSCRIPT = "application/postscript";
    public static final String MIME_APPLICATION_RDF_SMIL = "application/smil";
    public static final String MIME_APPLICATION_RDF_XML = "application/rdf+xml";
    public static final String MIME_APPLICATION_SRGS = "application/srgs";
    public static final String MIME_APPLICATION_SRGS_XML = "application/srgs+xml";
    public static final String MIME_APPLICATION_TGZ = "application/tgz";
    public static final String MIME_APPLICATION_VND_MIF = "application/vnd.mif";
    public static final String MIME_APPLICATION_VND_MOZZILLA_XUL_XML = "application/vnd.mozilla.xul+xml";
    public static final String MIME_APPLICATION_VND_MSEXCEL = "application/vnd.ms-excel";
    public static final String MIME_APPLICATION_VND_MSPOWERPOINT = "application/vnd.ms-powerpoint";
    public static final String MIME_APPLICATION_VND_RNREALMEDIA = "application/vnd.rn-realmedia";
    public static final String MIME_APPLICATION_XHTML_XML = "application/xhtml+xml";
    public static final String MIME_APPLICATION_XML = "application/xml";
    public static final String MIME_APPLICATION_XML_DTD = "application/xml-dtd";
    public static final String MIME_APPLICATION_XSLT_XML = "application/xslt+xml";
    public static final String MIME_APPLICATION_X_BCPIO = "application/x-bcpio";
    public static final String MIME_APPLICATION_X_CDLINK = "application/x-cdlink";
    public static final String MIME_APPLICATION_X_CHESS_PGN = "application/x-chess-pgn";
    public static final String MIME_APPLICATION_X_CPIO = "application/x-cpio";
    public static final String MIME_APPLICATION_X_CSH = "application/x-csh";
    public static final String MIME_APPLICATION_X_DIRECTOR = "application/x-director";
    public static final String MIME_APPLICATION_X_DVI = "application/x-dvi";
    public static final String MIME_APPLICATION_X_FUTURESPLASH = "application/x-futuresplash";
    public static final String MIME_APPLICATION_X_GTAR = "application/x-gtar";
    public static final String MIME_APPLICATION_X_GZIP = "application/x-gzip";
    public static final String MIME_APPLICATION_X_HDF = "application/x-hdf";
    public static final String MIME_APPLICATION_X_JAVASCRIPT = "application/x-javascript";
    public static final String MIME_APPLICATION_X_KOAN = "application/x-koan";
    public static final String MIME_APPLICATION_X_LATEX = "application/x-latex";
    public static final String MIME_APPLICATION_X_NETCDF = "application/x-netcdf";
    public static final String MIME_APPLICATION_X_OGG = "application/x-ogg";
    public static final String MIME_APPLICATION_X_RAR_COMPRESSED = "application/x-rar-compressed";
    public static final String MIME_APPLICATION_X_SH = "application/x-sh";
    public static final String MIME_APPLICATION_X_SHAR = "application/x-shar";
    public static final String MIME_APPLICATION_X_SHOCKWAVE_FLASH = "application/x-shockwave-flash";
    public static final String MIME_APPLICATION_X_STUFFIT = "application/x-stuffit";
    public static final String MIME_APPLICATION_X_SV4CPIO = "application/x-sv4cpio";
    public static final String MIME_APPLICATION_X_SV4CRC = "application/x-sv4crc";
    public static final String MIME_APPLICATION_X_TAR = "application/x-tar";
    public static final String MIME_APPLICATION_X_TCL = "application/x-tcl";
    public static final String MIME_APPLICATION_X_TEX = "application/x-tex";
    public static final String MIME_APPLICATION_X_TEXINFO = "application/x-texinfo";
    public static final String MIME_APPLICATION_X_TROFF = "application/x-troff";
    public static final String MIME_APPLICATION_X_TROFF_MAN = "application/x-troff-man";
    public static final String MIME_APPLICATION_X_TROFF_ME = "application/x-troff-me";
    public static final String MIME_APPLICATION_X_TROFF_MS = "application/x-troff-ms";
    public static final String MIME_APPLICATION_X_USTAR = "application/x-ustar";
    public static final String MIME_APPLICATION_X_WAIS_SOURCE = "application/x-wais-source";
    public static final String MIME_APPLICATION_ZIP = "application/zip";
    public static final String MIME_AUDIO_BASIC = "audio/basic";
    public static final String MIME_AUDIO_MIDI = "audio/midi";
    public static final String MIME_AUDIO_MPEG = "audio/mpeg";
    public static final String MIME_AUDIO_X_AIFF = "audio/x-aiff";
    public static final String MIME_AUDIO_X_MPEGURL = "audio/x-mpegurl";
    public static final String MIME_AUDIO_X_PN_REALAUDIO = "audio/x-pn-realaudio";
    public static final String MIME_AUDIO_X_WAV = "audio/x-wav";
    public static final String MIME_CHEMICAL_X_PDB = "chemical/x-pdb";
    public static final String MIME_CHEMICAL_X_XYZ = "chemical/x-xyz";
    public static final String MIME_IMAGE_BMP = "image/bmp";
    public static final String MIME_IMAGE_CGM = "image/cgm";
    public static final String MIME_IMAGE_GIF = "image/gif";
    public static final String MIME_IMAGE_IEF = "image/ief";
    public static final String MIME_IMAGE_JPEG = "image/jpeg";
    public static final String MIME_IMAGE_PNG = "image/png";
    public static final String MIME_IMAGE_SVG_XML = "image/svg+xml";
    public static final String MIME_IMAGE_TIFF = "image/tiff";
    public static final String MIME_IMAGE_VND_DJVU = "image/vnd.djvu";
    public static final String MIME_IMAGE_WAP_WBMP = "image/vnd.wap.wbmp";
    public static final String MIME_IMAGE_X_CMU_RASTER = "image/x-cmu-raster";
    public static final String MIME_IMAGE_X_ICON = "image/x-icon";
    public static final String MIME_IMAGE_X_PORTABLE_ANYMAP = "image/x-portable-anymap";
    public static final String MIME_IMAGE_X_PORTABLE_BITMAP = "image/x-portable-bitmap";
    public static final String MIME_IMAGE_X_PORTABLE_GRAYMAP = "image/x-portable-graymap";
    public static final String MIME_IMAGE_X_PORTABLE_PIXMAP = "image/x-portable-pixmap";
    public static final String MIME_IMAGE_X_RGB = "image/x-rgb";
    public static final String MIME_MODEL_IGES = "model/iges";
    public static final String MIME_MODEL_MESH = "model/mesh";
    public static final String MIME_MODEL_VRLM = "model/vrml";
    public static final String MIME_TEXT_CALENDAR = "text/calendar";
    public static final String MIME_TEXT_CSS = "text/css";
    public static final String MIME_TEXT_HTML = "text/html";
    public static final String MIME_TEXT_PLAIN = "text/plain";
    public static final String MIME_TEXT_RICHTEXT = "text/richtext";
    public static final String MIME_TEXT_RTF = "text/rtf";
    public static final String MIME_TEXT_SGML = "text/sgml";
    public static final String MIME_TEXT_TAB_SEPARATED_VALUES = "text/tab-separated-values";
    public static final String MIME_TEXT_VND_WAP_WMLSCRIPT = "text/vnd.wap.wmlscript";
    public static final String MIME_TEXT_VND_WAP_XML = "text/vnd.wap.wml";
    public static final String MIME_TEXT_X_COMPONENT = "text/x-component";
    public static final String MIME_TEXT_X_SETEXT = "text/x-setext";
    public static final String MIME_VIDEO_MPEG = "video/mpeg";
    public static final String MIME_VIDEO_QUICKTIME = "video/quicktime";
    public static final String MIME_VIDEO_VND_MPEGURL = "video/vnd.mpegurl";
    public static final String MIME_VIDEO_X_MSVIDEO = "video/x-msvideo";
    public static final String MIME_VIDEO_X_MS_WMV = "video/x-ms-wmv";
    public static final String MIME_VIDEO_X_SGI_MOVIE = "video/x-sgi-movie";
    public static final String MIME_X_CONFERENCE_X_COOLTALK = "x-conference/x-cooltalk";
    private static HashMap<String, String> mimeTypeMapping = new HashMap<String, String>(200) { // from class: com.naver.temy123.baseproject.base.Http.HWOkHttpMimeType.1
        {
            put1("xul", HWOkHttpMimeType.MIME_APPLICATION_VND_MOZZILLA_XUL_XML);
            put1("json", "application/json");
            put1("ice", HWOkHttpMimeType.MIME_X_CONFERENCE_X_COOLTALK);
            put1("movie", HWOkHttpMimeType.MIME_VIDEO_X_SGI_MOVIE);
            put1("avi", HWOkHttpMimeType.MIME_VIDEO_X_MSVIDEO);
            put1("wmv", HWOkHttpMimeType.MIME_VIDEO_X_MS_WMV);
            put1("m4u", HWOkHttpMimeType.MIME_VIDEO_VND_MPEGURL);
            put1("mxu", HWOkHttpMimeType.MIME_VIDEO_VND_MPEGURL);
            put1("htc", HWOkHttpMimeType.MIME_TEXT_X_COMPONENT);
            put1("etx", HWOkHttpMimeType.MIME_TEXT_X_SETEXT);
            put1("wmls", HWOkHttpMimeType.MIME_TEXT_VND_WAP_WMLSCRIPT);
            put1("wml", HWOkHttpMimeType.MIME_TEXT_VND_WAP_XML);
            put1("tsv", HWOkHttpMimeType.MIME_TEXT_TAB_SEPARATED_VALUES);
            put1("sgm", HWOkHttpMimeType.MIME_TEXT_SGML);
            put1("sgml", HWOkHttpMimeType.MIME_TEXT_SGML);
            put1("css", HWOkHttpMimeType.MIME_TEXT_CSS);
            put1("ifb", HWOkHttpMimeType.MIME_TEXT_CALENDAR);
            put1("ics", HWOkHttpMimeType.MIME_TEXT_CALENDAR);
            put1("wrl", HWOkHttpMimeType.MIME_MODEL_VRLM);
            put1("vrlm", HWOkHttpMimeType.MIME_MODEL_VRLM);
            put1("silo", HWOkHttpMimeType.MIME_MODEL_MESH);
            put1("mesh", HWOkHttpMimeType.MIME_MODEL_MESH);
            put1("msh", HWOkHttpMimeType.MIME_MODEL_MESH);
            put1("iges", HWOkHttpMimeType.MIME_MODEL_IGES);
            put1("igs", HWOkHttpMimeType.MIME_MODEL_IGES);
            put1("rgb", HWOkHttpMimeType.MIME_IMAGE_X_RGB);
            put1("ppm", HWOkHttpMimeType.MIME_IMAGE_X_PORTABLE_PIXMAP);
            put1("pgm", HWOkHttpMimeType.MIME_IMAGE_X_PORTABLE_GRAYMAP);
            put1("pbm", HWOkHttpMimeType.MIME_IMAGE_X_PORTABLE_BITMAP);
            put1("pnm", HWOkHttpMimeType.MIME_IMAGE_X_PORTABLE_ANYMAP);
            put1("ico", HWOkHttpMimeType.MIME_IMAGE_X_ICON);
            put1("ras", HWOkHttpMimeType.MIME_IMAGE_X_CMU_RASTER);
            put1("wbmp", HWOkHttpMimeType.MIME_IMAGE_WAP_WBMP);
            put1("djv", HWOkHttpMimeType.MIME_IMAGE_VND_DJVU);
            put1("djvu", HWOkHttpMimeType.MIME_IMAGE_VND_DJVU);
            put1("svg", HWOkHttpMimeType.MIME_IMAGE_SVG_XML);
            put1("ief", HWOkHttpMimeType.MIME_IMAGE_IEF);
            put1("cgm", HWOkHttpMimeType.MIME_IMAGE_CGM);
            put1("bmp", HWOkHttpMimeType.MIME_IMAGE_BMP);
            put1("xyz", HWOkHttpMimeType.MIME_CHEMICAL_X_XYZ);
            put1("pdb", HWOkHttpMimeType.MIME_CHEMICAL_X_PDB);
            put1("ra", HWOkHttpMimeType.MIME_AUDIO_X_PN_REALAUDIO);
            put1("ram", HWOkHttpMimeType.MIME_AUDIO_X_PN_REALAUDIO);
            put1("m3u", HWOkHttpMimeType.MIME_AUDIO_X_MPEGURL);
            put1("aifc", HWOkHttpMimeType.MIME_AUDIO_X_AIFF);
            put1("aif", HWOkHttpMimeType.MIME_AUDIO_X_AIFF);
            put1("aiff", HWOkHttpMimeType.MIME_AUDIO_X_AIFF);
            put1("mp3", HWOkHttpMimeType.MIME_AUDIO_MPEG);
            put1("mp2", HWOkHttpMimeType.MIME_AUDIO_MPEG);
            put1("mp1", HWOkHttpMimeType.MIME_AUDIO_MPEG);
            put1("mpga", HWOkHttpMimeType.MIME_AUDIO_MPEG);
            put1("kar", HWOkHttpMimeType.MIME_AUDIO_MIDI);
            put1("mid", HWOkHttpMimeType.MIME_AUDIO_MIDI);
            put1("midi", HWOkHttpMimeType.MIME_AUDIO_MIDI);
            put1("dtd", HWOkHttpMimeType.MIME_APPLICATION_XML_DTD);
            put1("xsl", HWOkHttpMimeType.MIME_APPLICATION_XML);
            put1("xml", HWOkHttpMimeType.MIME_APPLICATION_XML);
            put1("xslt", HWOkHttpMimeType.MIME_APPLICATION_XSLT_XML);
            put1("xht", HWOkHttpMimeType.MIME_APPLICATION_XHTML_XML);
            put1("xhtml", HWOkHttpMimeType.MIME_APPLICATION_XHTML_XML);
            put1("src", HWOkHttpMimeType.MIME_APPLICATION_X_WAIS_SOURCE);
            put1("ustar", HWOkHttpMimeType.MIME_APPLICATION_X_USTAR);
            put1("ms", HWOkHttpMimeType.MIME_APPLICATION_X_TROFF_MS);
            put1("me", HWOkHttpMimeType.MIME_APPLICATION_X_TROFF_ME);
            put1("man", HWOkHttpMimeType.MIME_APPLICATION_X_TROFF_MAN);
            put1("roff", HWOkHttpMimeType.MIME_APPLICATION_X_TROFF);
            put1("tr", HWOkHttpMimeType.MIME_APPLICATION_X_TROFF);
            put1("t", HWOkHttpMimeType.MIME_APPLICATION_X_TROFF);
            put1("texi", HWOkHttpMimeType.MIME_APPLICATION_X_TEXINFO);
            put1("texinfo", HWOkHttpMimeType.MIME_APPLICATION_X_TEXINFO);
            put1("tex", HWOkHttpMimeType.MIME_APPLICATION_X_TEX);
            put1("tcl", HWOkHttpMimeType.MIME_APPLICATION_X_TCL);
            put1("sv4crc", HWOkHttpMimeType.MIME_APPLICATION_X_SV4CRC);
            put1("sv4cpio", HWOkHttpMimeType.MIME_APPLICATION_X_SV4CPIO);
            put1("sit", HWOkHttpMimeType.MIME_APPLICATION_X_STUFFIT);
            put1("swf", HWOkHttpMimeType.MIME_APPLICATION_X_SHOCKWAVE_FLASH);
            put1("shar", HWOkHttpMimeType.MIME_APPLICATION_X_SHAR);
            put1("sh", HWOkHttpMimeType.MIME_APPLICATION_X_SH);
            put1("cdf", HWOkHttpMimeType.MIME_APPLICATION_X_NETCDF);
            put1("nc", HWOkHttpMimeType.MIME_APPLICATION_X_NETCDF);
            put1("latex", HWOkHttpMimeType.MIME_APPLICATION_X_LATEX);
            put1("skm", HWOkHttpMimeType.MIME_APPLICATION_X_KOAN);
            put1("skt", HWOkHttpMimeType.MIME_APPLICATION_X_KOAN);
            put1("skd", HWOkHttpMimeType.MIME_APPLICATION_X_KOAN);
            put1("skp", HWOkHttpMimeType.MIME_APPLICATION_X_KOAN);
            put1("js", HWOkHttpMimeType.MIME_APPLICATION_X_JAVASCRIPT);
            put1("hdf", HWOkHttpMimeType.MIME_APPLICATION_X_HDF);
            put1("gtar", HWOkHttpMimeType.MIME_APPLICATION_X_GTAR);
            put1("spl", HWOkHttpMimeType.MIME_APPLICATION_X_FUTURESPLASH);
            put1("dvi", HWOkHttpMimeType.MIME_APPLICATION_X_DVI);
            put1("dxr", HWOkHttpMimeType.MIME_APPLICATION_X_DIRECTOR);
            put1("dir", HWOkHttpMimeType.MIME_APPLICATION_X_DIRECTOR);
            put1("dcr", HWOkHttpMimeType.MIME_APPLICATION_X_DIRECTOR);
            put1("csh", HWOkHttpMimeType.MIME_APPLICATION_X_CSH);
            put1("cpio", HWOkHttpMimeType.MIME_APPLICATION_X_CPIO);
            put1("pgn", HWOkHttpMimeType.MIME_APPLICATION_X_CHESS_PGN);
            put1("vcd", HWOkHttpMimeType.MIME_APPLICATION_X_CDLINK);
            put1("bcpio", HWOkHttpMimeType.MIME_APPLICATION_X_BCPIO);
            put1("rm", HWOkHttpMimeType.MIME_APPLICATION_VND_RNREALMEDIA);
            put1("ppt", HWOkHttpMimeType.MIME_APPLICATION_VND_MSPOWERPOINT);
            put1("mif", HWOkHttpMimeType.MIME_APPLICATION_VND_MIF);
            put1("grxml", HWOkHttpMimeType.MIME_APPLICATION_SRGS_XML);
            put1("gram", HWOkHttpMimeType.MIME_APPLICATION_SRGS);
            put1("smil", HWOkHttpMimeType.MIME_APPLICATION_RDF_SMIL);
            put1("smi", HWOkHttpMimeType.MIME_APPLICATION_RDF_SMIL);
            put1("rdf", HWOkHttpMimeType.MIME_APPLICATION_RDF_XML);
            put1("ogg", HWOkHttpMimeType.MIME_APPLICATION_X_OGG);
            put1("oda", HWOkHttpMimeType.MIME_APPLICATION_ODA);
            put1("dmg", "application/octet-stream");
            put1("lzh", "application/octet-stream");
            put1("so", "application/octet-stream");
            put1("lha", "application/octet-stream");
            put1("dms", "application/octet-stream");
            put1("bin", "application/octet-stream");
            put1("mathml", HWOkHttpMimeType.MIME_APPLICATION_MATHML_XML);
            put1("cpt", HWOkHttpMimeType.MIME_APPLICATION_MAC_COMPACTPRO);
            put1("hqx", HWOkHttpMimeType.MIME_APPLICATION_MAC_BINHEX40);
            put1("jnlp", HWOkHttpMimeType.MIME_APPLICATION_JNLP);
            put1("ez", HWOkHttpMimeType.MIME_APPLICATION_ANDREW_INSET);
            put1("txt", "text/plain");
            put1("ini", "text/plain");
            put1("c", "text/plain");
            put1("h", "text/plain");
            put1("cpp", "text/plain");
            put1("cxx", "text/plain");
            put1("cc", "text/plain");
            put1("chh", "text/plain");
            put1("java", "text/plain");
            put1("csv", "text/plain");
            put1("bat", "text/plain");
            put1("cmd", "text/plain");
            put1("asc", "text/plain");
            put1("rtf", HWOkHttpMimeType.MIME_TEXT_RTF);
            put1("rtx", HWOkHttpMimeType.MIME_TEXT_RICHTEXT);
            put1("html", HWOkHttpMimeType.MIME_TEXT_HTML);
            put1("htm", HWOkHttpMimeType.MIME_TEXT_HTML);
            put1("zip", HWOkHttpMimeType.MIME_APPLICATION_ZIP);
            put1("rar", HWOkHttpMimeType.MIME_APPLICATION_X_RAR_COMPRESSED);
            put1("gzip", HWOkHttpMimeType.MIME_APPLICATION_X_GZIP);
            put1("gz", HWOkHttpMimeType.MIME_APPLICATION_X_GZIP);
            put1("tgz", HWOkHttpMimeType.MIME_APPLICATION_TGZ);
            put1("tar", HWOkHttpMimeType.MIME_APPLICATION_X_TAR);
            put1("gif", HWOkHttpMimeType.MIME_IMAGE_GIF);
            put1("jpeg", HWOkHttpMimeType.MIME_IMAGE_JPEG);
            put1("jpg", HWOkHttpMimeType.MIME_IMAGE_JPEG);
            put1("jpe", HWOkHttpMimeType.MIME_IMAGE_JPEG);
            put1("tiff", HWOkHttpMimeType.MIME_IMAGE_TIFF);
            put1("tif", HWOkHttpMimeType.MIME_IMAGE_TIFF);
            put1("png", HWOkHttpMimeType.MIME_IMAGE_PNG);
            put1("au", HWOkHttpMimeType.MIME_AUDIO_BASIC);
            put1("snd", HWOkHttpMimeType.MIME_AUDIO_BASIC);
            put1("wav", HWOkHttpMimeType.MIME_AUDIO_X_WAV);
            put1("mov", HWOkHttpMimeType.MIME_VIDEO_QUICKTIME);
            put1("qt", HWOkHttpMimeType.MIME_VIDEO_QUICKTIME);
            put1("mpeg", HWOkHttpMimeType.MIME_VIDEO_MPEG);
            put1("mpg", HWOkHttpMimeType.MIME_VIDEO_MPEG);
            put1("mpe", HWOkHttpMimeType.MIME_VIDEO_MPEG);
            put1("abs", HWOkHttpMimeType.MIME_VIDEO_MPEG);
            put1("doc", HWOkHttpMimeType.MIME_APPLICATION_MSWORD);
            put1("xls", HWOkHttpMimeType.MIME_APPLICATION_VND_MSEXCEL);
            put1("eps", HWOkHttpMimeType.MIME_APPLICATION_POSTSCRIPT);
            put1("ai", HWOkHttpMimeType.MIME_APPLICATION_POSTSCRIPT);
            put1("ps", HWOkHttpMimeType.MIME_APPLICATION_POSTSCRIPT);
            put1("pdf", HWOkHttpMimeType.MIME_APPLICATION_PDF);
            put1("exe", "application/octet-stream");
            put1("dll", "application/octet-stream");
            put1("class", "application/octet-stream");
            put1("jar", HWOkHttpMimeType.MIME_APPLICATION_JAVA_ARCHIVE);
        }

        private void put1(String str, String str2) {
            if (put(str, str2) != null) {
                throw new IllegalArgumentException("Duplicated extension: " + str);
            }
        }
    };

    public static void main(String[] strArr) {
        System.out.println(mimeTypeMapping.size());
    }

    public static void registerMimeType(String str, String str2) {
        mimeTypeMapping.put(str, str2);
    }

    public static String getMimeType(String str) {
        String lookupMimeType = lookupMimeType(str);
        return lookupMimeType == null ? "application/octet-stream" : lookupMimeType;
    }

    public static String lookupMimeType(String str) {
        return mimeTypeMapping.get(str.toLowerCase());
    }
}
